import type { BillingInvoice, BillingQuote, DocumentSnapshot } from "@/types/billing";
import { Money, StatusBadge } from "./BillingCommon";

type Doc = BillingQuote | BillingInvoice;
const fallback: DocumentSnapshot = { business_name: "Sky Designers", logo_url: "", website: "", email: "", phone: "", address: "", bank_name: "", account_name: "", account_number: "", branch: "" };
export default function DocumentPreview({ document, kind }: { document: Doc; kind: "quote" | "invoice" }) {
  const company = document.company_snapshot || fallback;
  const invoice = kind === "invoice" ? document as BillingInvoice : null;
  const quote = kind === "quote" ? document as BillingQuote : null;
  const client = document.client_snapshot || { name: document.client_name };
  return <article className="billing-document" aria-label={`${kind === "quote" ? "Quotation" : "Invoice"} preview`}>
    <header className="billing-document-header"><div>{company.logo_url ? <img src={company.logo_url} alt={`${company.business_name} logo`}/> : <span className="billing-document-logo">SD</span>}<h2>{company.business_name}</h2><p>{company.address}</p></div><div className="billing-document-title"><h1>{kind === "quote" ? "QUOTATION" : "INVOICE"}</h1><p>{kind === "quote" ? quote?.quote_number : invoice?.invoice_number}</p><StatusBadge status={document.status}/></div></header>
    <section className="billing-document-highlight"><span>{kind === "quote" ? "TOTAL" : "BALANCE DUE"}</span><strong><Money value={kind === "quote" ? document.total : invoice?.balance_due || 0} currency={document.currency}/></strong></section>
    <section className="billing-document-meta"><div><h3>Bill To</h3><strong>{String(client.name || document.client_name)}</strong>{[client.contact_person,client.billing_address,client.city,client.country,client.email,client.phone].filter(Boolean).map((v,i)=><p key={i}>{String(v)}</p>)}</div><dl>{kind === "quote" ? <><dt>Quote No</dt><dd>{quote?.quote_number}</dd><dt>Quote Date</dt><dd>{quote?.quote_date}</dd>{quote?.valid_until && <><dt>Valid Until</dt><dd>{quote.valid_until}</dd></>}</> : <><dt>Invoice No</dt><dd>{invoice?.invoice_number}</dd><dt>Invoice Date</dt><dd>{invoice?.invoice_date}</dd><dt>Due Date</dt><dd>{invoice?.due_date}</dd><dt>Terms</dt><dd>{invoice?.payment_terms || "-"}</dd></>}</dl></section>
    <table className="billing-document-items"><thead><tr><th>#</th><th>Service &amp; Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{document.items?.map((item,i)=><tr key={item.id || i}><td>{i+1}</td><td><strong>{item.service_title}</strong>{item.description && <p>{item.description}</p>}</td><td>{item.quantity}</td><td><Money value={item.unit_price} currency={document.currency}/></td><td><Money value={item.line_total} currency={document.currency}/></td></tr>)}</tbody></table>
    <section className="billing-document-totals"><dl><dt>Subtotal</dt><dd><Money value={document.subtotal} currency={document.currency}/></dd>{document.discount > 0 && <><dt>Discount</dt><dd>- <Money value={document.discount} currency={document.currency}/></dd></>}{document.tax > 0 && <><dt>Tax</dt><dd><Money value={document.tax} currency={document.currency}/></dd></>}<dt className="total">Total</dt><dd className="total"><Money value={document.total} currency={document.currency}/></dd>{invoice && <><dt>Amount Paid</dt><dd><Money value={invoice.amount_paid} currency={document.currency}/></dd><dt className="balance">Balance Due</dt><dd className="balance"><Money value={invoice.balance_due} currency={document.currency}/></dd></>}</dl></section>
    {(document.notes || document.terms) && <section className="billing-document-notes">{document.notes && <div><h3>Notes</h3><p>{document.notes}</p></div>}{document.terms && <div><h3>Terms &amp; Conditions</h3><p>{document.terms}</p></div>}</section>}
    {(company.bank_name || company.account_number) && <section className="billing-document-bank"><h3>Payment Details</h3><p><strong>{company.bank_name}</strong> - {company.branch}</p><p>{company.account_name} - {company.account_number}</p>{company.payment_instructions && <p>{company.payment_instructions}</p>}</section>}
    <footer><span>{company.business_name}</span><span>{[company.website,company.email,company.phone].filter(Boolean).join(" - ")}</span><span className="billing-page-number" /></footer>
  </article>;
}
