<?php
declare(strict_types=1);
require __DIR__.'/_bootstrap.php';
$action=defined('BILLING_ACTION')?BILLING_ACTION:'';$uid=(string)$billingUser['id'];
if($action==='invoices/archive'){billing_method(['POST']);$id=billing_id(billing_input()['id']??null);$db->prepare('UPDATE billing_invoices SET archived_at=UTC_TIMESTAMP() WHERE id=?')->execute([$id]);billing_audit($db,$uid,'invoice_archived','invoice',$id);billing_json(['success'=>true]);}
if($action==='quotes/archive'){billing_method(['POST']);$id=billing_id(billing_input()['id']??null);$db->prepare('UPDATE billing_quotes SET archived_at=UTC_TIMESTAMP() WHERE id=?')->execute([$id]);billing_audit($db,$uid,'quotation_archived','quote',$id);billing_json(['success'=>true]);}

function document_payload(array $d,string $kind): array { [$items,$subtotal]=billing_items($d);$discount=(float)($d['discount']??0);$tax=(float)($d['tax']??0);if($discount<0||$tax<0)billing_fail('Discount and tax cannot be negative.',422);$total=max(0,round($subtotal-$discount+$tax,2));$client=billing_id($d['client_id']??null);$currency=strtoupper(billing_text($d['currency']??'LKR',3));if(!preg_match('/^[A-Z]{3}$/',$currency))billing_fail('Currency must be a three-letter code.',422);$base=['client_id'=>$client,'subject'=>billing_text($d['subject']??'',255),'currency'=>$currency,'notes'=>billing_text($d['notes']??''),'terms'=>billing_text($d['terms']??''),'subtotal'=>$subtotal,'discount'=>$discount,'tax'=>$tax,'total'=>$total,'items'=>$items];if($kind==='quote'){$base['quote_date']=billing_date($d['quote_date']??null);$base['valid_until']=billing_date($d['valid_until']??null,true);if($base['subject']==='')billing_fail('Quotation subject is required.',422);}else{$base['invoice_date']=billing_date($d['invoice_date']??null);$base['due_date']=billing_date($d['due_date']??null);$base['payment_terms']=billing_text($d['payment_terms']??'',190);}return $base;}
function add_items(PDO $db,string $kind,int $id,array $items): void {$table=$kind==='quote'?'billing_quote_items':'billing_invoice_items';$fk=$kind.'_id';$s=$db->prepare("INSERT INTO $table($fk,service_title,description,quantity,unit_price,line_total,sort_order) VALUES(?,?,?,?,?,?,?)");foreach($items as $x)$s->execute([$id,$x['service_title'],$x['description'],$x['quantity'],$x['unit_price'],$x['line_total'],$x['sort_order']]);}
function decode_document(array $r): array {foreach(['company_snapshot','client_snapshot','payment_snapshot'] as $k)if(isset($r[$k])&&is_string($r[$k]))$r[$k]=json_decode($r[$k],true);foreach(['subtotal','discount','tax','total','amount_paid','balance_due'] as $k)if(isset($r[$k]))$r[$k]=(float)$r[$k];return $r;}
function get_quote(PDO $db,int $id): array {$q=billing_one($db,'SELECT q.*,c.name client_name FROM billing_quotes q JOIN billing_clients c ON c.id=q.client_id WHERE q.id=?',[$id]);if(!$q)billing_fail('Quotation not found.',404);$q=decode_document($q);$q['items']=billing_all($db,'SELECT * FROM billing_quote_items WHERE quote_id=? ORDER BY sort_order,id',[$id]);return $q;}
function get_invoice(PDO $db,int $id): array {$i=billing_one($db,billing_invoice_select().' WHERE i.id=?',[$id]);if(!$i)billing_fail('Invoice not found.',404);$i=decode_document($i);$i['items']=billing_all($db,'SELECT * FROM billing_invoice_items WHERE invoice_id=? ORDER BY sort_order,id',[$id]);$i['payments']=billing_all($db,'SELECT * FROM billing_payments WHERE invoice_id=? ORDER BY payment_date DESC,id DESC',[$id]);return $i;}

try {
if($action==='dashboard'){
 billing_method(['GET']);$today=gmdate('Y-m-d');$month=gmdate('Y-m-01');
 $paidMonth=(float)(billing_one($db,'SELECT COALESCE(SUM(amount),0) v FROM billing_payments WHERE reversed_at IS NULL AND payment_date>=?',[$month])['v']??0);$paidAll=(float)(billing_one($db,'SELECT COALESCE(SUM(amount),0) v FROM billing_payments WHERE reversed_at IS NULL')['v']??0);
 $tot=(float)(billing_one($db,"SELECT COALESCE(SUM(total),0) v FROM billing_invoices WHERE status<>'CANCELLED'")['v']??0);$out=(float)(billing_one($db,"SELECT COALESCE(SUM(GREATEST(i.total-COALESCE(p.paid,0),0)),0) v FROM billing_invoices i LEFT JOIN(SELECT invoice_id,SUM(amount) paid FROM billing_payments WHERE reversed_at IS NULL GROUP BY invoice_id)p ON p.invoice_id=i.id WHERE i.status<>'CANCELLED'")['v']??0);$over=(float)(billing_one($db,"SELECT COALESCE(SUM(GREATEST(i.total-COALESCE(p.paid,0),0)),0) v FROM billing_invoices i LEFT JOIN(SELECT invoice_id,SUM(amount) paid FROM billing_payments WHERE reversed_at IS NULL GROUP BY invoice_id)p ON p.invoice_id=i.id WHERE i.status<>'CANCELLED' AND i.due_date<?",[$today])['v']??0);
 $months=[];for($n=11;$n>=0;$n--){$start=(new DateTimeImmutable("first day of -$n month",new DateTimeZone('UTC')))->format('Y-m-d');$end=(new DateTimeImmutable($start))->modify('+1 month')->format('Y-m-d');$inv=(float)(billing_one($db,"SELECT COALESCE(SUM(total),0)v FROM billing_invoices WHERE status<>'CANCELLED' AND invoice_date>=? AND invoice_date<?",[$start,$end])['v']??0);$paid=(float)(billing_one($db,'SELECT COALESCE(SUM(amount),0)v FROM billing_payments WHERE reversed_at IS NULL AND payment_date>=? AND payment_date<?',[$start,$end])['v']??0);$months[]=['month'=>(new DateTimeImmutable($start))->format('M y'),'invoiced'=>$inv,'paid'=>$paid,'outstanding'=>max(0,$inv-$paid)];}
 $recentI=array_map('decode_document',billing_all($db,billing_invoice_select().' ORDER BY i.created_at DESC LIMIT 6'));$recentQ=array_map('decode_document',billing_all($db,'SELECT q.*,c.name client_name FROM billing_quotes q JOIN billing_clients c ON c.id=q.client_id ORDER BY q.created_at DESC LIMIT 6'));$outstanding=array_values(array_filter($recentI,fn($i)=>(float)$i['balance_due']>0&&$i['status']!=='CANCELLED'));
 billing_json(['success'=>true,'paid_this_month'=>$paidMonth,'paid_all_time'=>$paidAll,'total_invoiced'=>$tot,'outstanding'=>$out,'overdue'=>$over,'active_quotations'=>(int)(billing_one($db,"SELECT COUNT(*)v FROM billing_quotes WHERE status IN('DRAFT','SENT','ACCEPTED') AND archived_at IS NULL")['v']??0),'invoiced_this_month'=>(float)(billing_one($db,"SELECT COALESCE(SUM(total),0)v FROM billing_invoices WHERE status<>'CANCELLED' AND invoice_date>=?",[$month])['v']??0),'quotation_value'=>(float)(billing_one($db,"SELECT COALESCE(SUM(total),0)v FROM billing_quotes WHERE status NOT IN('REJECTED','EXPIRED')")['v']??0),'invoice_count'=>(int)(billing_one($db,'SELECT COUNT(*)v FROM billing_invoices')['v']??0),'paid_invoice_count'=>(int)(billing_one($db,"SELECT COUNT(*)v FROM billing_invoices WHERE status='PAID'")['v']??0),'overdue_invoice_count'=>(int)(billing_one($db,"SELECT COUNT(*)v FROM billing_invoices WHERE status='OVERDUE'")['v']??0),'monthly'=>$months,'recent_invoices'=>$recentI,'recent_quotes'=>$recentQ,'outstanding_invoices'=>$outstanding,'recent_payments'=>billing_all($db,'SELECT p.*,i.invoice_number,c.name client_name FROM billing_payments p JOIN billing_invoices i ON i.id=p.invoice_id JOIN billing_clients c ON c.id=p.client_id WHERE p.reversed_at IS NULL ORDER BY p.created_at DESC LIMIT 6')]);
}
if($action==='clients/list'){
 billing_method(['GET']);$q='%'.billing_text($_GET['search']??'',190).'%';$rows=billing_all($db,"SELECT c.*,COALESCE(x.invoiced,0)total_invoiced,COALESCE(x.paid,0)total_paid,COALESCE(x.invoiced,0)-COALESCE(x.paid,0)outstanding FROM billing_clients c LEFT JOIN(SELECT i.client_id,SUM(CASE WHEN i.status<>'CANCELLED' THEN i.total ELSE 0 END)invoiced,COALESCE(SUM(p.paid),0)paid FROM billing_invoices i LEFT JOIN(SELECT invoice_id,SUM(amount)paid FROM billing_payments WHERE reversed_at IS NULL GROUP BY invoice_id)p ON p.invoice_id=i.id GROUP BY i.client_id)x ON x.client_id=c.id WHERE c.name LIKE ? OR c.email LIKE ? OR c.phone LIKE ? ORDER BY c.is_active DESC,c.name",[$q,$q,$q]);foreach($rows as &$r)$r['is_active']=(bool)$r['is_active'];billing_json(['success'=>true,'clients'=>$rows]);
}
if($action==='clients/get'){
 billing_method(['GET']);$id=billing_id($_GET['id']??null);$client=billing_client($db,$id);billing_json(['success'=>true,'client'=>$client,'quotes'=>billing_all($db,'SELECT * FROM billing_quotes WHERE client_id=? ORDER BY quote_date DESC',[$id]),'invoices'=>billing_all($db,billing_invoice_select().' WHERE i.client_id=? ORDER BY i.invoice_date DESC',[$id]),'payments'=>billing_all($db,'SELECT p.*,i.invoice_number FROM billing_payments p JOIN billing_invoices i ON i.id=p.invoice_id WHERE p.client_id=? ORDER BY p.payment_date DESC',[$id])]);
}
if($action==='clients/save'){
 billing_method(['POST','PATCH']);$d=billing_input();$name=billing_text($d['name']??'',190);if($name==='')billing_fail('Client name is required.',422);$v=[$name,billing_text($d['contact_person']??'',190),billing_text($d['email']??'',255),billing_text($d['phone']??'',100),billing_text($d['billing_address']??''),billing_text($d['city']??'',120),billing_text($d['district']??'',120),billing_text($d['province']??'',120),billing_text($d['country']??'Sri Lanka',120),billing_text($d['postal_code']??'',30),billing_text($d['tax_identifier']??'',190),billing_text($d['notes']??'')];if(isset($d['id'])){$id=billing_id($d['id']);$v[]=$id;$db->prepare('UPDATE billing_clients SET name=?,contact_person=?,email=?,phone=?,billing_address=?,city=?,district=?,province=?,country=?,postal_code=?,tax_identifier=?,notes=? WHERE id=?')->execute($v);$event='client_updated';}else{$v[]=$uid;$db->prepare('INSERT INTO billing_clients(name,contact_person,email,phone,billing_address,city,district,province,country,postal_code,tax_identifier,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($v);$id=(int)$db->lastInsertId();$event='client_created';}billing_audit($db,$uid,$event,'client',$id);billing_json(['success'=>true,'client'=>billing_client($db,$id)]);
}
if($action==='clients/archive'){billing_method(['POST']);$id=billing_id(billing_input()['id']??null);$db->prepare('UPDATE billing_clients SET is_active=0 WHERE id=?')->execute([$id]);billing_audit($db,$uid,'client_archived','client',$id);billing_json(['success'=>true]);}

if($action==='quotes/list'){
 billing_method(['GET']);$q='%'.billing_text($_GET['search']??'',190).'%';$status=billing_text($_GET['status']??'',30);$sql="SELECT q.*,c.name client_name FROM billing_quotes q JOIN billing_clients c ON c.id=q.client_id WHERE q.archived_at IS NULL AND (q.quote_number LIKE ? OR c.name LIKE ? OR q.subject LIKE ? OR CAST(q.total AS CHAR) LIKE ?)";$p=[$q,$q,$q,$q];if($status!==''){$sql.=' AND q.status=?';$p[]=$status;}$sql.=' ORDER BY q.quote_date DESC,q.id DESC LIMIT 250';billing_json(['success'=>true,'quotes'=>array_map('decode_document',billing_all($db,$sql,$p))]);
}
if($action==='quotes/get'){billing_method(['GET']);$id=billing_id($_GET['id']??null);billing_json(['success'=>true,'quote'=>get_quote($db,$id),'activity'=>billing_all($db,"SELECT * FROM billing_activity_log WHERE entity_type='quote' AND entity_id=? ORDER BY created_at DESC",[$id])]);}
if($action==='quotes/create'){
 billing_method(['POST']);$raw=billing_input();$d=document_payload($raw,'quote');$issue=($raw['status']??'DRAFT')==='SENT';$client=billing_client($db,$d['client_id']);$settings=billing_settings($db);$db->beginTransaction();$no=billing_allocate($db,'quote');$s=$db->prepare("INSERT INTO billing_quotes(quote_number,client_id,subject,quote_date,valid_until,currency,status,issued_at,notes,terms,subtotal,discount,tax,total,company_snapshot,client_snapshot,payment_snapshot,created_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$s->execute([$no,$d['client_id'],$d['subject'],$d['quote_date'],$d['valid_until'],$d['currency'],$issue?'SENT':'DRAFT',$issue?gmdate('Y-m-d H:i:s'):null,$d['notes'],$d['terms']?:$settings['default_quotation_terms'],$d['subtotal'],$d['discount'],$d['tax'],$d['total'],json_encode(billing_snapshot($settings)),json_encode($client),json_encode(billing_snapshot($settings)),$uid]);$id=(int)$db->lastInsertId();add_items($db,'quote',$id,$d['items']);billing_audit($db,$uid,$issue?'quotation_sent':'quotation_created','quote',$id);$db->commit();billing_json(['success'=>true,'quote'=>get_quote($db,$id)],201);
}
if($action==='quotes/update'){
 billing_method(['PATCH']);$raw=billing_input();$id=billing_id($raw['id']??null);$d=document_payload($raw,'quote');$old=get_quote($db,$id);if($old['status']!=='DRAFT')billing_fail('Only draft quotations can be edited. Duplicate issued quotations instead.',409);$db->beginTransaction();$db->prepare('UPDATE billing_quotes SET client_id=?,subject=?,quote_date=?,valid_until=?,currency=?,notes=?,terms=?,subtotal=?,discount=?,tax=?,total=? WHERE id=?')->execute([$d['client_id'],$d['subject'],$d['quote_date'],$d['valid_until'],$d['currency'],$d['notes'],$d['terms'],$d['subtotal'],$d['discount'],$d['tax'],$d['total'],$id]);$db->prepare('DELETE FROM billing_quote_items WHERE quote_id=?')->execute([$id]);add_items($db,'quote',$id,$d['items']);billing_audit($db,$uid,'quotation_updated','quote',$id);$db->commit();billing_json(['success'=>true,'quote'=>get_quote($db,$id)]);
}
if($action==='quotes/status'){
 billing_method(['POST']);$d=billing_input();$id=billing_id($d['id']??null);$status=billing_text($d['status']??'',30);if(!in_array($status,['DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED'],true))billing_fail('Invalid quotation status.',422);$quote=get_quote($db,$id);if($status==='SENT'&&!$quote['issued_at']){$settings=billing_settings($db);$client=billing_client($db,(int)$quote['client_id']);$db->prepare('UPDATE billing_quotes SET status=?,issued_at=UTC_TIMESTAMP(),company_snapshot=?,client_snapshot=?,payment_snapshot=? WHERE id=? AND status<>\'CONVERTED\'')->execute([$status,json_encode(billing_snapshot($settings)),json_encode($client),json_encode(billing_snapshot($settings)),$id]);}else{$db->prepare('UPDATE billing_quotes SET status=? WHERE id=? AND status<>\'CONVERTED\'')->execute([$status,$id]);}billing_audit($db,$uid,'quotation_status_changed','quote',$id,['status'=>$status]);billing_json(['success'=>true,'quote'=>get_quote($db,$id)]);
}
if($action==='quotes/duplicate'){
 billing_method(['POST']);$source=get_quote($db,billing_id(billing_input()['id']??null));$source['quote_date']=gmdate('Y-m-d');$source['valid_until']=null;$d=document_payload($source,'quote');$client=billing_client($db,$d['client_id']);$settings=billing_settings($db);$db->beginTransaction();$no=billing_allocate($db,'quote');$db->prepare("INSERT INTO billing_quotes(quote_number,client_id,subject,quote_date,valid_until,currency,status,notes,terms,subtotal,discount,tax,total,company_snapshot,client_snapshot,payment_snapshot,created_by)VALUES(?,?,?,?,?,?,'DRAFT',?,?,?,?,?,?,?,?,?,?)")->execute([$no,$d['client_id'],$d['subject'],$d['quote_date'],$d['valid_until'],$d['currency'],$d['notes'],$d['terms'],$d['subtotal'],$d['discount'],$d['tax'],$d['total'],json_encode(billing_snapshot($settings)),json_encode($client),json_encode(billing_snapshot($settings)),$uid]);$id=(int)$db->lastInsertId();add_items($db,'quote',$id,$d['items']);billing_audit($db,$uid,'quotation_duplicated','quote',$id,['source_id'=>$source['id']]);$db->commit();billing_json(['success'=>true,'quote'=>get_quote($db,$id)],201);
}
if($action==='quotes/convert'){
 billing_method(['POST']);$qid=billing_id(billing_input()['id']??null);$q=get_quote($db,$qid);if($q['status']==='CONVERTED')billing_fail('Quotation has already been converted.',409);$db->beginTransaction();$locked=billing_one($db,'SELECT status FROM billing_quotes WHERE id=? FOR UPDATE',[$qid]);if($locked['status']==='CONVERTED')billing_fail('Quotation has already been converted.',409);$no=billing_allocate($db,'invoice');$due=(new DateTimeImmutable('today'))->modify('+30 days')->format('Y-m-d');$db->prepare("INSERT INTO billing_invoices(invoice_number,client_id,subject,invoice_date,due_date,payment_terms,currency,status,subtotal,discount,tax,total,notes,terms,company_snapshot,client_snapshot,payment_snapshot,source_quote_id,created_by)VALUES(?,?,?,?,?,?,?,'DRAFT',?,?,?,?,?,?,?,?,?,?,?)")->execute([$no,$q['client_id'],$q['subject'],gmdate('Y-m-d'),$due,'30 days',$q['currency'],$q['subtotal'],$q['discount'],$q['tax'],$q['total'],$q['notes'],$q['terms'],json_encode($q['company_snapshot']),json_encode($q['client_snapshot']),json_encode($q['payment_snapshot']),$qid,$uid]);$iid=(int)$db->lastInsertId();add_items($db,'invoice',$iid,$q['items']);$db->prepare("UPDATE billing_quotes SET status='CONVERTED' WHERE id=?")->execute([$qid]);billing_audit($db,$uid,'converted_to_invoice','quote',$qid,['invoice_id'=>$iid]);billing_audit($db,$uid,'invoice_created_from_quote','invoice',$iid,['quote_id'=>$qid]);$db->commit();billing_json(['success'=>true,'invoice'=>get_invoice($db,$iid)],201);
}

if($action==='invoices/list'){
 billing_method(['GET']);$q='%'.billing_text($_GET['search']??'',190).'%';$status=billing_text($_GET['status']??'',30);$sql=billing_invoice_select()." WHERE i.archived_at IS NULL AND (i.invoice_number LIKE ? OR c.name LIKE ? OR i.subject LIKE ? OR CAST(i.total AS CHAR) LIKE ?)";$p=[$q,$q,$q,$q];if($status!==''){$sql.=' AND i.status=?';$p[]=$status;}if(($_GET['outstanding']??'')==='1')$sql.=" AND i.status<>'CANCELLED' AND i.total>COALESCE(p.amount_paid,0)";$sql.=' ORDER BY i.invoice_date DESC,i.id DESC LIMIT 250';billing_json(['success'=>true,'invoices'=>array_map('decode_document',billing_all($db,$sql,$p))]);
}
if($action==='invoices/get'){billing_method(['GET']);$id=billing_id($_GET['id']??null);billing_refresh_invoice($db,$id);billing_json(['success'=>true,'invoice'=>get_invoice($db,$id),'activity'=>billing_all($db,"SELECT * FROM billing_activity_log WHERE entity_type='invoice' AND entity_id=? ORDER BY created_at DESC",[$id])]);}
if($action==='invoices/create'){
 billing_method(['POST']);$raw=billing_input();$d=document_payload($raw,'invoice');$issue=($raw['status']??'DRAFT')==='SENT';$client=billing_client($db,$d['client_id']);$settings=billing_settings($db);$db->beginTransaction();$no=billing_allocate($db,'invoice');$db->prepare("INSERT INTO billing_invoices(invoice_number,client_id,subject,invoice_date,due_date,payment_terms,currency,status,issued_at,subtotal,discount,tax,total,notes,terms,company_snapshot,client_snapshot,payment_snapshot,created_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$no,$d['client_id'],$d['subject'],$d['invoice_date'],$d['due_date'],$d['payment_terms']?:$settings['default_invoice_terms'],$d['currency'],$issue?'SENT':'DRAFT',$issue?gmdate('Y-m-d H:i:s'):null,$d['subtotal'],$d['discount'],$d['tax'],$d['total'],$d['notes'],$d['terms']?:$settings['default_invoice_conditions'],json_encode(billing_snapshot($settings)),json_encode($client),json_encode(billing_snapshot($settings)),$uid]);$id=(int)$db->lastInsertId();add_items($db,'invoice',$id,$d['items']);billing_audit($db,$uid,$issue?'invoice_issued':'invoice_created','invoice',$id);$db->commit();billing_json(['success'=>true,'invoice'=>get_invoice($db,$id)],201);
}
if($action==='invoices/update'){
 billing_method(['PATCH']);$raw=billing_input();$id=billing_id($raw['id']??null);$old=get_invoice($db,$id);if($old['status']!=='DRAFT')billing_fail('Only draft invoices can be edited. Cancel issued invoices to preserve financial history.',409);$d=document_payload($raw,'invoice');$db->beginTransaction();$db->prepare('UPDATE billing_invoices SET client_id=?,subject=?,invoice_date=?,due_date=?,payment_terms=?,currency=?,subtotal=?,discount=?,tax=?,total=?,notes=?,terms=? WHERE id=?')->execute([$d['client_id'],$d['subject'],$d['invoice_date'],$d['due_date'],$d['payment_terms'],$d['currency'],$d['subtotal'],$d['discount'],$d['tax'],$d['total'],$d['notes'],$d['terms'],$id]);$db->prepare('DELETE FROM billing_invoice_items WHERE invoice_id=?')->execute([$id]);add_items($db,'invoice',$id,$d['items']);billing_refresh_invoice($db,$id);billing_audit($db,$uid,'invoice_updated','invoice',$id);$db->commit();billing_json(['success'=>true,'invoice'=>get_invoice($db,$id)]);
}
if($action==='invoices/status'){billing_method(['POST']);$d=billing_input();$id=billing_id($d['id']??null);$status=billing_text($d['status']??'',30);if(!in_array($status,['DRAFT','SENT','CANCELLED'],true))billing_fail('Status is calculated from payments or is invalid.',422);$invoice=get_invoice($db,$id);if($status==='SENT'&&!$invoice['issued_at']){$settings=billing_settings($db);$client=billing_client($db,(int)$invoice['client_id']);$db->prepare('UPDATE billing_invoices SET status=?,issued_at=UTC_TIMESTAMP(),company_snapshot=?,client_snapshot=?,payment_snapshot=? WHERE id=?')->execute([$status,json_encode(billing_snapshot($settings)),json_encode($client),json_encode(billing_snapshot($settings)),$id]);}else{$db->prepare('UPDATE billing_invoices SET status=? WHERE id=?')->execute([$status,$id]);}billing_audit($db,$uid,$status==='CANCELLED'?'invoice_cancelled':($status==='SENT'?'invoice_issued':'invoice_status_changed'),'invoice',$id,['status'=>$status]);billing_json(['success'=>true]);}
if($action==='invoices/delete'){billing_method(['DELETE']);$id=billing_id(billing_input()['id']??null);$db->beginTransaction();$invoice=billing_one($db,'SELECT * FROM billing_invoices WHERE id=? FOR UPDATE',[$id]);if(!$invoice)billing_fail('Invoice not found.',404);$payments=(int)(billing_one($db,'SELECT COUNT(*) v FROM billing_payments WHERE invoice_id=?',[$id])['v']??0);if($invoice['status']!=='DRAFT'||$payments>0)billing_fail('Only draft invoices without payment history can be deleted. Cancel or archive this invoice instead.',409);$number=$invoice['invoice_number'];$db->prepare('DELETE FROM billing_invoices WHERE id=?')->execute([$id]);billing_audit($db,$uid,'draft_invoice_deleted','invoice',$id,['invoice_number'=>$number]);$db->commit();billing_json(['success'=>true]);}
if($action==='quotes/delete'){billing_method(['DELETE']);$id=billing_id(billing_input()['id']??null);$db->beginTransaction();$quote=billing_one($db,'SELECT * FROM billing_quotes WHERE id=? FOR UPDATE',[$id]);if(!$quote)billing_fail('Quotation not found.',404);if($quote['status']!=='DRAFT')billing_fail('Only unconverted draft quotations can be deleted. Archive this quotation instead.',409);$number=$quote['quote_number'];$db->prepare('DELETE FROM billing_quotes WHERE id=?')->execute([$id]);billing_audit($db,$uid,'draft_quotation_deleted','quote',$id,['quote_number'=>$number]);$db->commit();billing_json(['success'=>true]);}

if($action==='payments/list'){billing_method(['GET']);$q='%'.billing_text($_GET['search']??'',190).'%';billing_json(['success'=>true,'payments'=>billing_all($db,'SELECT p.*,i.invoice_number,c.name client_name FROM billing_payments p JOIN billing_invoices i ON i.id=p.invoice_id JOIN billing_clients c ON c.id=p.client_id WHERE i.invoice_number LIKE ? OR c.name LIKE ? OR p.reference_number LIKE ? ORDER BY p.payment_date DESC,p.id DESC LIMIT 500',[$q,$q,$q])]);}
if($action==='payments/create'){
 billing_method(['POST']);$d=billing_input();$iid=billing_id($d['invoice_id']??null);$amount=(float)($d['amount']??0);$method=billing_text($d['payment_method']??'',30);if(!in_array($method,['Bank Transfer','Cash','Card','Other'],true))billing_fail('Invalid payment method.',422);$db->beginTransaction();billing_one($db,'SELECT id FROM billing_invoices WHERE id=? FOR UPDATE',[$iid]);$invoice=get_invoice($db,$iid);if($invoice['status']==='CANCELLED'||$invoice['status']==='DRAFT')billing_fail('Issue the invoice before recording a payment.',409);if($amount<=0||$amount>(float)$invoice['balance_due'])billing_fail('Payment must be positive and cannot exceed the current balance.',422);$db->prepare('INSERT INTO billing_payments(invoice_id,client_id,payment_date,amount,payment_method,reference_number,notes,created_by)VALUES(?,?,?,?,?,?,?,?)')->execute([$iid,$invoice['client_id'],billing_date($d['payment_date']??null),$amount,$method,billing_text($d['reference_number']??'',190),billing_text($d['notes']??''),$uid]);$id=(int)$db->lastInsertId();billing_refresh_invoice($db,$iid);billing_audit($db,$uid,'payment_added','payment',$id,['invoice_id'=>$iid,'amount'=>$amount]);$db->commit();billing_json(['success'=>true,'payment'=>billing_one($db,'SELECT * FROM billing_payments WHERE id=?',[$id])],201);
}
if($action==='payments/reverse'){
 billing_method(['POST']);$d=billing_input();$id=billing_id($d['id']??null);$reason=billing_text($d['reason']??'',500);if($reason==='')billing_fail('A reversal reason is required.',422);$p=billing_one($db,'SELECT * FROM billing_payments WHERE id=?',[$id]);if(!$p)billing_fail('Payment not found.',404);if($p['reversed_at'])billing_fail('Payment is already reversed.',409);$db->beginTransaction();$db->prepare('UPDATE billing_payments SET reversed_at=CURRENT_TIMESTAMP,reversed_by=?,reversal_reason=? WHERE id=? AND reversed_at IS NULL')->execute([$uid,$reason,$id]);billing_refresh_invoice($db,(int)$p['invoice_id']);billing_audit($db,$uid,'payment_reversed','payment',$id,['invoice_id'=>(int)$p['invoice_id'],'reason'=>$reason]);$db->commit();billing_json(['success'=>true]);
}
if($action==='settings/get'){billing_method(['GET']);billing_json(['success'=>true,'settings'=>billing_settings($db)]);}
if($action==='settings/update'){
 billing_method(['PATCH']);$d=billing_input();$allowed=['business_name','display_name','logo_url','primary_color','accent_color','website','email','phone','address','country','registration_number','quotation_prefix','invoice_prefix','default_currency','default_invoice_terms','default_quote_validity','default_due_days','quotation_footer_message','invoice_footer_message','bank_name','account_name','account_number','branch','payment_instructions','default_quotation_terms','default_invoice_conditions','disclaimer','footer_company_text','footer_show_registration'];$sets=[];$values=[];foreach($allowed as $k)if(array_key_exists($k,$d)){$sets[]="$k=?";$values[]=in_array($k,['default_quote_validity','default_due_days','footer_show_registration'],true)?max(0,(int)$d[$k]):billing_text($d[$k],$k==='logo_url'?2048:10000);}foreach(['quotation_next_number','invoice_next_number'] as $k)if(array_key_exists($k,$d)){$v=(int)$d[$k];$current=(int)(billing_settings($db)[$k]??1);if($v<$current)billing_fail('Next document number cannot be reduced or reused.',422);$sets[]="$k=?";$values[]=$v;}if(!$sets)billing_fail('No settings supplied.',422);$values[]=$uid;$db->prepare('UPDATE billing_settings SET '.implode(',',$sets).',updated_by=? WHERE id=1')->execute($values);billing_audit($db,$uid,'settings_changed','settings',1,['fields'=>array_keys($d)]);billing_json(['success'=>true,'settings'=>billing_settings($db)]);
}
billing_fail('Endpoint not found.',404);
} catch(PDOException $e){if($db->inTransaction())$db->rollBack();error_log('Billing database error: '.$e->getCode());billing_fail('The billing operation could not be completed.',500);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Billing error: '.$e->getMessage());billing_fail('The billing operation could not be completed.',500);}
